version: '3'
services:
  auth-service:
    build:
      context: ./microservice
    networks:
      - app-network
    depends_on:
      - database

  api-gateway:
    build:
      context: ./APIGATEWAY
    networks:
      - app-network
    ports:
      - 4000:4000
    depends_on:
      - auth-service

  database:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
